//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_default p__default;
        
        private static SteamVR_Input_ActionSet_platformer p_platformer;
        
        private static SteamVR_Input_ActionSet_buggy p_buggy;
        
        private static SteamVR_Input_ActionSet_mixedreality p_mixedreality;
        
        private static SteamVR_Input_ActionSet_robot p_robot;
        
        private static SteamVR_Input_ActionSet_preface p_preface;
        
        private static SteamVR_Input_ActionSet_menu p_menu;
        
        public static SteamVR_Input_ActionSet_default _default
        {
            get
            {
                return SteamVR_Actions.p__default.GetCopy<SteamVR_Input_ActionSet_default>();
            }
        }
        
        public static SteamVR_Input_ActionSet_platformer platformer
        {
            get
            {
                return SteamVR_Actions.p_platformer.GetCopy<SteamVR_Input_ActionSet_platformer>();
            }
        }
        
        public static SteamVR_Input_ActionSet_buggy buggy
        {
            get
            {
                return SteamVR_Actions.p_buggy.GetCopy<SteamVR_Input_ActionSet_buggy>();
            }
        }
        
        public static SteamVR_Input_ActionSet_mixedreality mixedreality
        {
            get
            {
                return SteamVR_Actions.p_mixedreality.GetCopy<SteamVR_Input_ActionSet_mixedreality>();
            }
        }
        
        public static SteamVR_Input_ActionSet_robot robot
        {
            get
            {
                return SteamVR_Actions.p_robot.GetCopy<SteamVR_Input_ActionSet_robot>();
            }
        }
        
        public static SteamVR_Input_ActionSet_preface preface
        {
            get
            {
                return SteamVR_Actions.p_preface.GetCopy<SteamVR_Input_ActionSet_preface>();
            }
        }
        
        public static SteamVR_Input_ActionSet_menu menu
        {
            get
            {
                return SteamVR_Actions.p_menu.GetCopy<SteamVR_Input_ActionSet_menu>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p__default = ((SteamVR_Input_ActionSet_default)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_default>("/actions/default")));
            SteamVR_Actions.p_platformer = ((SteamVR_Input_ActionSet_platformer)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_platformer>("/actions/platformer")));
            SteamVR_Actions.p_buggy = ((SteamVR_Input_ActionSet_buggy)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_buggy>("/actions/buggy")));
            SteamVR_Actions.p_mixedreality = ((SteamVR_Input_ActionSet_mixedreality)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_mixedreality>("/actions/mixedreality")));
            SteamVR_Actions.p_robot = ((SteamVR_Input_ActionSet_robot)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_robot>("/actions/robot")));
            SteamVR_Actions.p_preface = ((SteamVR_Input_ActionSet_preface)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_preface>("/actions/preface")));
            SteamVR_Actions.p_menu = ((SteamVR_Input_ActionSet_menu)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_menu>("/actions/menu")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions._default,
                    SteamVR_Actions.platformer,
                    SteamVR_Actions.buggy,
                    SteamVR_Actions.mixedreality,
                    SteamVR_Actions.robot,
                    SteamVR_Actions.preface,
                    SteamVR_Actions.menu};
        }
    }
}
