/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.RosSharp
{
    public class DefaultWandState : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "ros_sharp/DefaultWandState";

        public Header header;
        public byte interactUI;
        public byte teleport;
        public byte grabPinch;
        public byte grabGrip;
        public float squeeze;

        public DefaultWandState()
        {
            this.header = new Header();
            this.interactUI = 0;
            this.teleport = 0;
            this.grabPinch = 0;
            this.grabGrip = 0;
            this.squeeze = 0.0f;
        }

        public DefaultWandState(Header header, byte interactUI, byte teleport, byte grabPinch, byte grabGrip, float squeeze)
        {
            this.header = header;
            this.interactUI = interactUI;
            this.teleport = teleport;
            this.grabPinch = grabPinch;
            this.grabGrip = grabGrip;
            this.squeeze = squeeze;
        }
    }
}
