/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.RosSharp
{
    public class RobotWandState : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "ros_sharp/RobotWandState";

        public Header header;
        public byte mode;
        public byte grip;
        public byte trigger;
        public float squeeze;
        public float[] stearing;
        public byte teleport;
        public byte up;
        public byte down;
        public byte left;
        public byte right;
        public byte system;

        public RobotWandState()
        {
            this.header = new Header();
            this.mode = 0;
            this.grip = 0;
            this.trigger = 0;
            this.squeeze = 0.0f;
            this.stearing = new float[0];
            this.teleport = 0;
            this.up = 0;
            this.down = 0;
            this.left = 0;
            this.right = 0;
            this.system = 0;
        }

        public RobotWandState(Header header, byte mode, byte grip, byte trigger, float squeeze, float[] stearing, byte teleport, byte up, byte down, byte left, byte right, byte system)
        {
            this.header = header;
            this.mode = mode;
            this.grip = grip;
            this.trigger = trigger;
            this.squeeze = squeeze;
            this.stearing = stearing;
            this.teleport = teleport;
            this.up = up;
            this.down = down;
            this.left = left;
            this.right = right;
            this.system = system;
        }
    }
}
