//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_preface : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Next
        {
            get
            {
                return SteamVR_Actions.preface_Next;
            }
        }
        
        public virtual SteamVR_Action_Boolean Skip
        {
            get
            {
                return SteamVR_Actions.preface_Skip;
            }
        }
        
        public virtual SteamVR_Action_Boolean ResetView
        {
            get
            {
                return SteamVR_Actions.preface_ResetView;
            }
        }
        
        public virtual SteamVR_Action_Boolean Restart
        {
            get
            {
                return SteamVR_Actions.preface_Restart;
            }
        }
    }
}
