//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_robot : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Mode
        {
            get
            {
                return SteamVR_Actions.robot_Mode;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.robot_Grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean Trigger
        {
            get
            {
                return SteamVR_Actions.robot_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.robot_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Stearing
        {
            get
            {
                return SteamVR_Actions.robot_Stearing;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.robot_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean Up
        {
            get
            {
                return SteamVR_Actions.robot_Up;
            }
        }
        
        public virtual SteamVR_Action_Boolean Down
        {
            get
            {
                return SteamVR_Actions.robot_Down;
            }
        }
        
        public virtual SteamVR_Action_Boolean Left
        {
            get
            {
                return SteamVR_Actions.robot_Left;
            }
        }
        
        public virtual SteamVR_Action_Boolean Right
        {
            get
            {
                return SteamVR_Actions.robot_Right;
            }
        }
        
        public virtual SteamVR_Action_Boolean System
        {
            get
            {
                return SteamVR_Actions.robot_System;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.robot_Haptic;
            }
        }
    }
}
